# Generated by Django 3.0.6 on 2020-05-23 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('mypage_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mypage_pwd', models.CharField(blank=True, max_length=100, null=True)),
                ('mypage_url', models.URLField(blank=True, null=True)),
                ('progress', models.CharField(blank=True, max_length=100, null=True)),
                ('next_datetime', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
