# Generated by Django 3.0.6 on 2020-05-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20200527_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='next_date',
            field=models.DateField(blank=True, null=True, verbose_name='サンプル項目1 日付'),
        ),
        migrations.AddField(
            model_name='company',
            name='next_time',
            field=models.TimeField(blank=True, null=True, verbose_name='サンプル項目3 日時'),
        ),
        migrations.AlterField(
            model_name='company',
            name='next_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='サンプル項目2 日付時刻'),
        ),
    ]
