# Generated by Django 3.0.6 on 2020-05-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20200529_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='next_datetime',
        ),
        migrations.AlterField(
            model_name='company',
            name='mypage_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='マイページID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mypage_pwd',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='マイページパスワード'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mypage_url',
            field=models.URLField(blank=True, null=True, verbose_name='マイページURL'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='企業名'),
        ),
        migrations.AlterField(
            model_name='company',
            name='next_date',
            field=models.DateField(blank=True, null=True, verbose_name='次回選考日程'),
        ),
        migrations.AlterField(
            model_name='company',
            name='next_time',
            field=models.TimeField(blank=True, null=True, verbose_name='選考時間'),
        ),
        migrations.AlterField(
            model_name='company',
            name='progress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='選考状況'),
        ),
    ]
